"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_PERSONAL_TOKEN"
"base_url": "https://andriy.api.crowdin.com"
"preserve_hierarchy": true

files: 
  - "source": "/res/values/strings.xml"
    "translation": "/res/values-%two_letters_code%/strings.xml"
  - "source": "/Localizable.xcstrings"
    "translation": "%original_file_name%"
    "multilingual": 1
